//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Components.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WfErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WfErrorCode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Components.Properties.WfErrorCode", typeof(WfErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不存在该节点 ,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1000 {
            get {
                return ResourceManager.GetString("Error_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点已关闭 ,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1001 {
            get {
                return ResourceManager.GetString("Error_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点已冻结,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1002 {
            get {
                return ResourceManager.GetString("Error_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点不在活动状态,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1003 {
            get {
                return ResourceManager.GetString("Error_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点不存在或不在活动状态,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1004 {
            get {
                return ResourceManager.GetString("Error_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点已完成,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1005 {
            get {
                return ResourceManager.GetString("Error_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点已停止,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1006 {
            get {
                return ResourceManager.GetString("Error_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该节点不是审核节点，(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1007 {
            get {
                return ResourceManager.GetString("Error_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前操作人在该节点无操作权限，(TemplateId:{0};BusinessId:{1};NodeCode:{2};EmployeeId:{3}) 的本地化字符串。
        /// </summary>
        public static string Error_1008 {
            get {
                return ResourceManager.GetString("Error_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回节点为空,(BusinessId:{0},NodeCode{1}) 的本地化字符串。
        /// </summary>
        public static string Error_1009 {
            get {
                return ResourceManager.GetString("Error_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 对象为空,请检查对象引用 的本地化字符串。
        /// </summary>
        public static string Error_2000 {
            get {
                return ResourceManager.GetString("Error_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段为空(NULL),请检查字段值 的本地化字符串。
        /// </summary>
        public static string Error_2001 {
            get {
                return ResourceManager.GetString("Error_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段为空(Empty),请检查字段值 的本地化字符串。
        /// </summary>
        public static string Error_2002 {
            get {
                return ResourceManager.GetString("Error_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段小于等于零,请检查字段值 的本地化字符串。
        /// </summary>
        public static string Error_2003 {
            get {
                return ResourceManager.GetString("Error_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制流程失败，请检查失败原因(TemplateId:{0}) 的本地化字符串。
        /// </summary>
        public static string Error_3000 {
            get {
                return ResourceManager.GetString("Error_3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取入口节点失败，请检查失败原因(TemplateId:{0};BusinessId:{1};) 的本地化字符串。
        /// </summary>
        public static string Error_3001 {
            get {
                return ResourceManager.GetString("Error_3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取下一步节点失败，请检查失败原因(TemplateId:{0};BusinessId:{1};NodeCode:{2}) 的本地化字符串。
        /// </summary>
        public static string Error_3002 {
            get {
                return ResourceManager.GetString("Error_3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程开始初始化失败，请检查失败原因(TemplateId:{0};BusinessId:{1};) 的本地化字符串。
        /// </summary>
        public static string Error_3003 {
            get {
                return ResourceManager.GetString("Error_3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程提交失败，请检查失败原因(TemplateId:{0};BusinessId:{1};NodeCode:{2}) 的本地化字符串。
        /// </summary>
        public static string Error_3004 {
            get {
                return ResourceManager.GetString("Error_3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程退回失败，请检查失败原因(TemplateId:{0};BusinessId:{1};NodeCode:{2}) 的本地化字符串。
        /// </summary>
        public static string Error_3005 {
            get {
                return ResourceManager.GetString("Error_3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选签节点的下一步节点未汇总，(TemplateId:{0};BusinessId:{1};NodeCode:{2}) 的本地化字符串。
        /// </summary>
        public static string Error_4001 {
            get {
                return ResourceManager.GetString("Error_4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集合删除对象失败，(TemplateId:{0};BusinessId:{1};NodeCode:{2}) 的本地化字符串。
        /// </summary>
        public static string Error_5001 {
            get {
                return ResourceManager.GetString("Error_5001", resourceCulture);
            }
        }
    }
}
